#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "openfs/link.h"
typedef struct{uint8_t*b;uint32_t bs;uint64_t bc;}D;
static openfs_io_result_t r(void*c,uint64_t f,uint32_t n,void*x){D*d=c;if(f>=d->bc||(uint64_t)n>d->bc-f)return OPENFS_IO_OUT_OF_RANGE;memcpy(x,d->b+(size_t)(f*d->bs),(size_t)((uint64_t)n*d->bs));return OPENFS_IO_OK;}
static openfs_io_result_t w(void*c,uint64_t f,uint32_t n,const void*x){D*d=c;if(f>=d->bc||(uint64_t)n>d->bc-f)return OPENFS_IO_OUT_OF_RANGE;memcpy(d->b+(size_t)(f*d->bs),x,(size_t)((uint64_t)n*d->bs));return OPENFS_IO_OK;}
static openfs_io_result_t f(void*c){(void)c;return OPENFS_IO_OK;}
int main(void){D d={0};d.bs=4096U;d.bc=512U;d.b=calloc((size_t)d.bs,d.bc);assert(d.b);openfs_block_device_t v={&d,d.bs,d.bc,r,w,f};uint8_t u[16]={0};assert(openfs_format(&v,u)==OPENFS_FORMAT_OK);openfs_superblock_t s;assert(openfs_read_superblock(&v,&s)==OPENFS_FORMAT_OK);uint64_t a=0,b=0,q=0;assert(openfs_path_create(&v,&s,"/a",OPENFS_INODE_MODE_REGULAR,&a)==OPENFS_PATH_OK);assert(openfs_link(&v,&s,"/a","/b")==OPENFS_PATH_OK);assert(openfs_path_lookup(&v,&s,"/b",&b)==OPENFS_PATH_OK&&a==b);assert(openfs_path_unlink(&v,&s,"/a")==OPENFS_PATH_OK);assert(openfs_path_lookup(&v,&s,"/b",&b)==OPENFS_PATH_OK&&a==b);assert(openfs_symlink(&v,&s,"/b","/link")==OPENFS_PATH_OK);char out[16];assert(openfs_readlink(&v,&s,"/link",out,sizeof(out))==OPENFS_PATH_OK&&strcmp(out,"/b")==0);assert(openfs_resolve_symlink(&v,&s,"/link",out,sizeof(out),0U)==OPENFS_PATH_OK&&strcmp(out,"/b")==0);assert(openfs_path_mkdir(&v,&s,"/dir",&a)==OPENFS_PATH_OK);assert(openfs_path_create(&v,&s,"/dir/file",OPENFS_INODE_MODE_REGULAR,&b)==OPENFS_PATH_OK);assert(openfs_symlink(&v,&s,"/dir/file","/filelink")==OPENFS_PATH_OK);assert(openfs_path_lookup_follow(&v,&s,"/filelink",&q)==OPENFS_PATH_OK&&q==b);assert(openfs_symlink(&v,&s,"/dir","/dirlink")==OPENFS_PATH_OK);assert(openfs_path_lookup_follow(&v,&s,"/dirlink/file",&q)==OPENFS_PATH_OK&&q==b);assert(openfs_symlink(&v,&s,"file","/dir/rellink")==OPENFS_PATH_OK);assert(openfs_path_lookup_follow(&v,&s,"/dir/rellink",&q)==OPENFS_PATH_OK&&q==b);assert(openfs_symlink(&v,&s,"/dir/file","/dir/abslink")==OPENFS_PATH_OK);assert(openfs_path_lookup_follow(&v,&s,"/dir/abslink",&q)==OPENFS_PATH_OK&&q==b);for(int i=0;i<39;i++){char lp[16],tp[16];(void)snprintf(lp,sizeof(lp),"/l%d",i);(void)snprintf(tp,sizeof(tp),"/l%d",i+1);assert(openfs_symlink(&v,&s,tp,lp)==OPENFS_PATH_OK);}assert(openfs_symlink(&v,&s,"/dir/file","/l39")==OPENFS_PATH_OK);assert(openfs_path_lookup_follow(&v,&s,"/l0",&q)==OPENFS_PATH_OK&&q==b);assert(openfs_symlink(&v,&s,"/l0","/l40")==OPENFS_PATH_OK);assert(openfs_path_lookup_follow(&v,&s,"/l40",&q)==OPENFS_PATH_CORRUPT);assert(openfs_path_unlink(&v,&s,"/link")==OPENFS_PATH_OK);assert(openfs_path_unlink(&v,&s,"/b")==OPENFS_PATH_OK);assert(openfs_path_lookup(&v,&s,"/b",&b)==OPENFS_PATH_NOT_FOUND);free(d.b);return 0;}