#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "openfs/bitmap.h"
#include "openfs/format.h"
#include "openfs/inode.h"
#include "openfs/extent.h"
#include "openfs/inode_alloc.h"

typedef struct { uint8_t *bytes; uint32_t block_size; uint64_t block_count; uint64_t fail_block; int fail_write_once_after_copy; } disk_t;
static openfs_io_result_t rd(void*c,uint64_t f,uint32_t n,void*b){disk_t*d=c;if(n==0U||f>=d->block_count||(uint64_t)n>d->block_count-f)return OPENFS_IO_OUT_OF_RANGE;uint64_t o=f*d->block_size,l=(uint64_t)n*d->block_size;memcpy(b,d->bytes+(size_t)o,(size_t)l);return OPENFS_IO_OK;}
static openfs_io_result_t wr(void*c,uint64_t f,uint32_t n,const void*b){disk_t*d=c;if(n==0U||f>=d->block_count||(uint64_t)n>d->block_count-f)return OPENFS_IO_OUT_OF_RANGE;uint64_t o=f*d->block_size,l=(uint64_t)n*d->block_size;memcpy(d->bytes+(size_t)o,b,(size_t)l);if(d->fail_write_once_after_copy&&f==d->fail_block){d->fail_write_once_after_copy=0;return OPENFS_IO_IO_ERROR;}return OPENFS_IO_OK;}
static openfs_io_result_t fl(void*c){(void)c;return OPENFS_IO_OK;}
int main(void){
 disk_t d={.block_size=4096U,.block_count=128U};d.bytes=calloc((size_t)d.block_count,d.block_size);assert(d.bytes);
 openfs_block_device_t v={&d,d.block_size,d.block_count,rd,wr,fl};uint8_t uuid[16]={1U};
 assert(openfs_format(&v,uuid)==OPENFS_FORMAT_OK);
 openfs_superblock_t sb;assert(openfs_read_superblock(&v,&sb)==OPENFS_FORMAT_OK);
 int used=0;assert(openfs_bitmap_test(&v,sb.inode_bitmap_start,sb.inode_bitmap_blocks,0U,&used)==OPENFS_BITMAP_OK);assert(used==1);
 uint64_t inode_count=(sb.inode_table_blocks*(uint64_t)sb.block_size)/OPENFS_INODE_SIZE;
 openfs_inode_t root;assert(openfs_inode_read(&v,sb.inode_table_start,1U,inode_count,&root)==OPENFS_INODE_OK);
 assert(root.inode_number==1U&&root.parent_inode==1U&&root.link_count==1U&&root.mode==(OPENFS_INODE_MODE_DIRECTORY|0755U));
root.mode=0200000U|0644U;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.mode=OPENFS_INODE_MODE_DIRECTORY|0755U;root.flags=0x80000000U;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.flags=OPENFS_INODE_FLAG_INLINE_DATA|OPENFS_INODE_FLAG_HAS_EXTENTS;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.flags=OPENFS_INODE_FLAG_INLINE_DATA;root.mode=OPENFS_INODE_MODE_REGULAR|0755U;root.size=1U;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.mode=OPENFS_INODE_MODE_SYMLINK|0777U;root.size=sizeof(root.inline_data)+1U;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.size=0U;root.flags=OPENFS_INODE_FLAG_EXTENT_TREE;root.extent_count=OPENFS_INODE_TREE_INLINE_EXTENT_MAX;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.flags=OPENFS_INODE_FLAG_HAS_EXTENTS;root.extent_count=0U;root.blocks=0U;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.mode=OPENFS_INODE_MODE_DIRECTORY|0755U;root.flags=0U;root.extent_count=0U;root.parent_inode=0U;assert(openfs_inode_validate(&root,inode_count)==OPENFS_INODE_CORRUPT);root.parent_inode=1U;
 root.size=0U;root.generation=2U;assert(openfs_inode_write(&v,sb.inode_table_start,inode_count,&root)==OPENFS_INODE_OK);
 memset(&root,0,sizeof(root));assert(openfs_inode_read(&v,sb.inode_table_start,1U,inode_count,&root)==OPENFS_INODE_OK);assert(root.size==0U&&root.generation==2U);
 assert(openfs_bitmap_set(&v,sb.inode_bitmap_start,sb.inode_bitmap_blocks,1U,1)==OPENFS_BITMAP_OK);
 assert(openfs_bitmap_test(&v,sb.inode_bitmap_start,sb.inode_bitmap_blocks,1U,&used)==OPENFS_BITMAP_OK&&used==1);openfs_inode_t many=root;memset(many.inline_data,0,sizeof(many.inline_data));memset(many.reserved,0,sizeof(many.reserved));many.inode_number=2U;many.generation=1U;many.parent_inode=1U;many.link_count=1U;many.mode=OPENFS_INODE_MODE_REGULAR;many.blocks=(uint64_t)OPENFS_INODE_INLINE_EXTENT_MAX*25U;many.flags=OPENFS_INODE_FLAG_HAS_EXTENTS;many.extent_count=0U;for(uint32_t k=0U;k<OPENFS_INODE_INLINE_EXTENT_MAX;k++){openfs_extent_t e={((uint64_t)k)*25U,((uint64_t)k)*100U+50U,25U};assert(openfs_inode_set_extent(&many,k,&e)==OPENFS_EXTENT_OK);}openfs_inode_t malformed=many;openfs_extent_t bad_extent={125U,150U,25U};assert(openfs_inode_set_extent(&malformed,1U,&bad_extent)==OPENFS_EXTENT_OK);assert(openfs_inode_validate(&malformed,inode_count)==OPENFS_INODE_CORRUPT);assert(openfs_inode_write(&v,sb.inode_table_start,inode_count,&many)==OPENFS_INODE_OK);memset(&many,0,sizeof(many));
 openfs_inode_t inode3_before;assert(openfs_inode_read(&v,sb.inode_table_start,3U,inode_count,&inode3_before)==OPENFS_INODE_OK);uint64_t inode3_block=sb.inode_table_start+((3U-1U)*(uint64_t)OPENFS_INODE_SIZE)/sb.block_size;d.fail_block=inode3_block;d.fail_write_once_after_copy=1;uint64_t failed=0U;assert(openfs_inode_alloc(&v,&sb,1U,OPENFS_INODE_MODE_REGULAR,&failed)==OPENFS_INODE_ALLOC_IO_ERROR);assert(failed==0U);assert(openfs_bitmap_test(&v,sb.inode_bitmap_start,sb.inode_bitmap_blocks,2U,&used)==OPENFS_BITMAP_OK&&used==0);openfs_inode_t inode3;assert(openfs_inode_read(&v,sb.inode_table_start,3U,inode_count,&inode3)==OPENFS_INODE_OK);assert(memcmp(&inode3,&inode3_before,sizeof(inode3))==0&&inode3.inode_number==3U&&inode3.mode==OPENFS_INODE_MODE_FREE&&inode3.link_count==0U);assert(openfs_inode_read(&v,sb.inode_table_start,2U,inode_count,&many)==OPENFS_INODE_OK);assert(many.extent_count==OPENFS_INODE_INLINE_EXTENT_MAX);for(uint32_t k=0U;k<OPENFS_INODE_INLINE_EXTENT_MAX;k++){openfs_extent_t e={0};assert(openfs_inode_get_extent(&many,k,&e)==OPENFS_EXTENT_OK&&e.physical_start==((uint64_t)k)*100U+50U&&e.block_count==25U);}
 openfs_inode_t free_candidate;uint64_t free_candidate_number=0U;assert(openfs_inode_alloc(&v,&sb,1U,OPENFS_INODE_MODE_REGULAR,&free_candidate_number)==OPENFS_INODE_ALLOC_OK);assert(free_candidate_number==3U);assert(openfs_inode_read(&v,sb.inode_table_start,free_candidate_number,inode_count,&free_candidate)==OPENFS_INODE_OK);free_candidate.mode=OPENFS_INODE_MODE_FREE;free_candidate.link_count=0U;assert(openfs_inode_write(&v,sb.inode_table_start,inode_count,&free_candidate)==OPENFS_INODE_OK);openfs_inode_t free_before=free_candidate;uint64_t inode_bitmap_block=sb.inode_bitmap_start+((free_candidate_number-1U)/8U)/sb.block_size;d.fail_block=inode_bitmap_block;d.fail_write_once_after_copy=1;assert(openfs_inode_free(&v,&sb,free_candidate_number)==OPENFS_INODE_ALLOC_IO_ERROR);assert(openfs_inode_read(&v,sb.inode_table_start,free_candidate_number,inode_count,&free_candidate)==OPENFS_INODE_OK);assert(memcmp(&free_candidate,&free_before,sizeof(free_candidate))==0);assert(openfs_bitmap_test(&v,sb.inode_bitmap_start,sb.inode_bitmap_blocks,free_candidate_number-1U,&used)==OPENFS_BITMAP_OK&&used==1);d.fail_block=sb.inode_table_start+((free_candidate_number-1U)*(uint64_t)OPENFS_INODE_SIZE)/sb.block_size;d.fail_write_once_after_copy=1;assert(openfs_inode_free(&v,&sb,free_candidate_number)==OPENFS_INODE_ALLOC_IO_ERROR);assert(openfs_inode_read(&v,sb.inode_table_start,free_candidate_number,inode_count,&free_candidate)==OPENFS_INODE_OK);assert(memcmp(&free_candidate,&free_before,sizeof(free_candidate))==0);assert(openfs_bitmap_test(&v,sb.inode_bitmap_start,sb.inode_bitmap_blocks,free_candidate_number-1U,&used)==OPENFS_BITMAP_OK&&used==1);
 openfs_inode_t inode;memset(&inode,0,sizeof(inode));free(d.bytes);inode.uid=1000U;inode.gid=100U;inode.mode=OPENFS_INODE_MODE_REGULAR|0640U;assert(openfs_inode_check_access(&inode,1000U,200U,4U)==OPENFS_INODE_OK);assert(openfs_inode_check_access(&inode,1000U,200U,2U)==OPENFS_INODE_OK);assert(openfs_inode_check_access(&inode,2000U,100U,4U)==OPENFS_INODE_OK);assert(openfs_inode_check_access(&inode,2000U,100U,2U)==OPENFS_INODE_ACCESS_DENIED);assert(openfs_inode_check_access(&inode,2000U,200U,4U)==OPENFS_INODE_ACCESS_DENIED);assert(openfs_inode_check_access(&inode,2000U,200U,8U)==OPENFS_INODE_INVALID_ARGUMENT);return 0;
}
