#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "openfs/journal.h"
#include "openfs/crc32c.h"
typedef struct{uint8_t*b;uint32_t bs;uint64_t bc;}D;
static openfs_io_result_t r(void*c,uint64_t f,uint32_t n,void*x){D*d=c;if(f>=d->bc||(uint64_t)n>d->bc-f)return OPENFS_IO_OUT_OF_RANGE;memcpy(x,d->b+(size_t)(f*d->bs),(size_t)((uint64_t)n*d->bs));return OPENFS_IO_OK;}
static openfs_io_result_t w(void*c,uint64_t f,uint32_t n,const void*x){D*d=c;if(f>=d->bc||(uint64_t)n>d->bc-f)return OPENFS_IO_OUT_OF_RANGE;memcpy(d->b+(size_t)(f*d->bs),x,(size_t)((uint64_t)n*d->bs));return OPENFS_IO_OK;}
static openfs_io_result_t f(void*c){(void)c;return OPENFS_IO_OK;}
static openfs_journal_result_t cb(void*c,uint64_t tx,const uint8_t*p,uint32_t n){uint32_t *hits=c;assert(tx==1U&&n==3U&&memcmp(p,"abc",3U)==0);(*hits)++;return OPENFS_JOURNAL_OK;}
int main(void){D d={0};d.bs=4096U;d.bc=256U;d.b=calloc((size_t)d.bs,d.bc);assert(d.b);openfs_block_device_t v={&d,d.bs,d.bc,r,w,f};uint8_t u[16]={0};assert(openfs_format(&v,u)==OPENFS_FORMAT_OK);openfs_superblock_t s;assert(openfs_read_superblock(&v,&s)==OPENFS_FORMAT_OK);openfs_journal_t j;assert(openfs_journal_open(&j,&v,&s)==OPENFS_JOURNAL_OK);uint64_t tx=0;j.transaction_id=UINT64_MAX;assert(openfs_journal_begin(&j,&v,&tx)==OPENFS_JOURNAL_FULL);j.transaction_id=0U;j.sequence=UINT64_MAX;assert(openfs_journal_begin(&j,&v,&tx)==OPENFS_JOURNAL_FULL);j.sequence=0U;assert(openfs_journal_begin(&j,&v,&tx)==OPENFS_JOURNAL_OK&&tx==1U);j.sequence=UINT64_MAX;assert(openfs_journal_write(&j,&v,tx,"abc",3U)==OPENFS_JOURNAL_FULL);assert(openfs_journal_commit(&j,&v,tx)==OPENFS_JOURNAL_FULL);j.sequence=0U;assert(openfs_journal_begin(&j,&v,&tx)==OPENFS_JOURNAL_INVALID_ARGUMENT);assert(openfs_journal_write(&j,&v,2U,"abc",3U)==OPENFS_JOURNAL_INVALID_ARGUMENT);assert(openfs_journal_write(&j,&v,tx,"abc",3U)==OPENFS_JOURNAL_OK);uint32_t hits=0;assert(openfs_journal_replay(&v,&s,cb,&hits)==OPENFS_JOURNAL_OK&&hits==0U);assert(openfs_journal_commit(&j,&v,2U)==OPENFS_JOURNAL_INVALID_ARGUMENT);assert(openfs_journal_commit(&j,&v,tx)==OPENFS_JOURNAL_OK);assert(openfs_journal_replay(&v,&s,cb,&hits)==OPENFS_JOURNAL_OK&&hits==1U);assert(openfs_journal_checkpoint(&j,&v)==OPENFS_JOURNAL_OK);uint8_t orphan_data[4096]={0};memcpy(orphan_data,"OJNL1",5U);orphan_data[5]=OPENFS_JOURNAL_DATA;orphan_data[8]=99U;orphan_data[16]=1U;orphan_data[24]=1U;orphan_data[32]=0x5AU;uint32_t orphan_crc=openfs_crc32c(orphan_data,4092U);orphan_data[28]=(uint8_t)orphan_crc;orphan_data[29]=(uint8_t)(orphan_crc>>8U);orphan_data[30]=(uint8_t)(orphan_crc>>16U);orphan_data[31]=(uint8_t)(orphan_crc>>24U);assert(v.write(v.context,s.journal_start,1U,orphan_data)==OPENFS_IO_OK);assert(openfs_journal_replay(&v,&s,cb,&hits)==OPENFS_JOURNAL_CORRUPT);assert(openfs_journal_checkpoint(&j,&v)==OPENFS_JOURNAL_OK);uint8_t bad[4096]={0};memcpy(bad,"OJNL1",5U);bad[5]=OPENFS_JOURNAL_COMMIT;bad[8]=99U;uint32_t crc=openfs_crc32c(bad,4092U);bad[28]=(uint8_t)crc;bad[29]=(uint8_t)(crc>>8U);bad[30]=(uint8_t)(crc>>16U);bad[31]=(uint8_t)(crc>>24U);assert(v.write(v.context,s.journal_start,1U,bad)==OPENFS_IO_OK);assert(openfs_journal_replay(&v,&s,cb,&hits)==OPENFS_JOURNAL_CORRUPT);assert(openfs_journal_checkpoint(&j,&v)==OPENFS_JOURNAL_OK);assert(openfs_journal_begin(&j,&v,&tx)==OPENFS_JOURNAL_OK&&tx==2U);while(j.next_record+1U<j.journal_blocks)assert(openfs_journal_write(&j,&v,tx,"x",1U)==OPENFS_JOURNAL_OK);uint8_t block[4096]={0};uint64_t before=j.next_record;assert(openfs_journal_write_block(&j,&v,tx,s.journal_start,block)==OPENFS_JOURNAL_FULL);assert(j.next_record==before);assert(openfs_journal_commit(&j,&v,tx)==OPENFS_JOURNAL_OK);assert(openfs_journal_checkpoint(&j,&v)==OPENFS_JOURNAL_OK);free(d.b);return 0;}