#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "openfs/format.h"
#include "openfs/mount.h"
#include "openfs/path.h"
#include "openfs/file.h"
#include "openfs/inode.h"
#include "openfs/scrub.h"
typedef struct{uint8_t*b;uint32_t bs;uint64_t n;}D;static openfs_io_result_t r(void*c,uint64_t f,uint32_t n,void*o){D*d=c;if(f>=d->n||(uint64_t)n>d->n-f)return OPENFS_IO_OUT_OF_RANGE;memcpy(o,d->b+(size_t)f*d->bs,(size_t)n*d->bs);return OPENFS_IO_OK;}static openfs_io_result_t w(void*c,uint64_t f,uint32_t n,const void*i){D*d=c;if(f>=d->n||(uint64_t)n>d->n-f)return OPENFS_IO_OUT_OF_RANGE;memcpy(d->b+(size_t)f*d->bs,i,(size_t)n*d->bs);return OPENFS_IO_OK;}static openfs_io_result_t fl(void*c){(void)c;return OPENFS_IO_OK;}int main(void){D x={0};x.bs=4096;x.n=256;x.b=calloc((size_t)x.bs,x.n);assert(x.b);openfs_block_device_t d={&x,x.bs,x.n,r,w,fl};uint8_t u[16]={1};assert(openfs_format(&d,u)==OPENFS_FORMAT_OK);openfs_mount_t m={0};assert(openfs_mount(&m,&d)==OPENFS_MOUNT_OK);assert((m.superblock.feature_flags&OPENFS_FEATURE_DATA_CHECKSUM)!=0);uint64_t ino=0;assert(openfs_path_create(&d,&m.superblock,"/f",OPENFS_INODE_MODE_REGULAR,&ino)==OPENFS_PATH_OK);uint64_t ic=m.superblock.inode_table_blocks*(uint64_t)m.superblock.block_size/OPENFS_INODE_SIZE;openfs_inode_t in;assert(openfs_inode_read(&d,m.superblock.inode_table_start,ino,ic,&in)==OPENFS_INODE_OK);uint8_t z[4096];memset(z,0x5a,sizeof(z));assert(openfs_file_write(&d,&m.superblock,&in,0,z,sizeof(z))==OPENFS_FILE_OK);uint8_t out[4096];size_t got=0;assert(openfs_file_read(&d,&m.superblock,&in,0,out,sizeof(out),&got)==OPENFS_FILE_OK&&got==sizeof(out)&&memcmp(z,out,sizeof(z))==0);openfs_extent_t e;assert(openfs_inode_get_extent(&in,0,&e)==OPENFS_EXTENT_OK);x.b[(size_t)e.physical_start*x.bs]^=1U;got=0;assert(openfs_file_read(&d,&m.superblock,&in,0,out,sizeof(out),&got)==OPENFS_FILE_CORRUPT);uint64_t errors=0;assert(openfs_scrub(&d,&m.superblock,&errors)==OPENFS_SCRUB_CORRUPT&&errors>0);assert(openfs_unmount(&m)==OPENFS_MOUNT_OK);free(x.b);return 0;}