#include "openfs/inode.h"
#include "openfs/extent.h"
#include <stdlib.h>
#include <string.h>
#include "openfs/crc32c.h"
#define INODE_MAGIC_OFFSET 216U
#define INODE_CHECKSUM_OFFSET 224U
static uint32_t g32(const uint8_t*p){return (uint32_t)p[0]|((uint32_t)p[1]<<8U)|((uint32_t)p[2]<<16U)|((uint32_t)p[3]<<24U);}
static uint64_t g64(const uint8_t*p){uint64_t v=0U;for(unsigned i=0U;i<8U;i++)v|=(uint64_t)p[i]<<(8U*i);return v;}
static void p32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8U);p[2]=(uint8_t)(v>>16U);p[3]=(uint8_t)(v>>24U);}
static void p64(uint8_t*p,uint64_t v){for(unsigned i=0U;i<8U;i++)p[i]=(uint8_t)(v>>(8U*i));}
static void encode(const openfs_inode_t*i,uint8_t*b){memset(b,0,OPENFS_INODE_SIZE);memcpy(b+INODE_MAGIC_OFFSET,"OINODE1\0",8U);p64(b,i->inode_number);p64(b+8,i->generation);p64(b+16,i->size);p64(b+24,i->blocks);p64(b+32,i->parent_inode);p64(b+40,i->link_count);p64(b+48,i->atime_ns);p64(b+56,i->mtime_ns);p64(b+64,i->ctime_ns);p32(b+72,i->mode);p32(b+76,i->flags);p32(b+80,i->uid);p32(b+84,i->gid);p32(b+88,i->extent_count);p32(b+92,i->reserved0);if((i->flags&OPENFS_INODE_FLAG_INLINE_DATA)!=0U){memcpy(b+96,i->inline_data,80U);}else{memcpy(b+96,i->reserved,120U);}p32(b+INODE_CHECKSUM_OFFSET,0U);p32(b+INODE_CHECKSUM_OFFSET,openfs_crc32c(b,INODE_CHECKSUM_OFFSET));}
static int decode(const uint8_t*b,openfs_inode_t*i){if(memcmp(b+INODE_MAGIC_OFFSET,"OINODE1\0",8U)!=0)return 0;uint32_t stored=g32(b+INODE_CHECKSUM_OFFSET);uint8_t c[OPENFS_INODE_SIZE];memcpy(c,b,sizeof(c));p32(c+INODE_CHECKSUM_OFFSET,0U);if(stored!=openfs_crc32c(c,INODE_CHECKSUM_OFFSET))return 0;i->inode_number=g64(b);i->generation=g64(b+8);i->size=g64(b+16);i->blocks=g64(b+24);i->parent_inode=g64(b+32);i->link_count=g64(b+40);i->atime_ns=g64(b+48);i->mtime_ns=g64(b+56);i->ctime_ns=g64(b+64);i->mode=g32(b+72);i->flags=g32(b+76);i->uid=g32(b+80);i->gid=g32(b+84);i->extent_count=g32(b+88);i->reserved0=g32(b+92);memset(i->inline_data,0U,sizeof(i->inline_data));memset(i->reserved,0U,sizeof(i->reserved));if((i->flags&OPENFS_INODE_FLAG_INLINE_DATA)!=0U){memcpy(i->inline_data,b+96,80U);}else{memcpy(i->reserved,b+96,120U);}return 1;}
static int locate(const openfs_block_device_t*d,uint64_t start,uint64_t inode_number,uint64_t count,uint64_t*block,uint32_t*within){if(inode_number==0U||inode_number>count||inode_number-1U>UINT64_MAX/OPENFS_INODE_SIZE)return 0;uint64_t off=(inode_number-1U)*(uint64_t)OPENFS_INODE_SIZE;*block=off/d->block_size;*within=(uint32_t)(off%d->block_size);if(*within+OPENFS_INODE_SIZE>d->block_size)return 0;if(start>UINT64_MAX-*block)return 0;if(start+*block>=d->block_count)return 0;return 1;}
openfs_inode_result_t openfs_inode_validate(const openfs_inode_t*i,uint64_t count){if(i==NULL||i->inode_number==0U||i->inode_number>count)return OPENFS_INODE_INVALID_ARGUMENT;if(i->generation==0U)return OPENFS_INODE_CORRUPT;if(i->mode!=OPENFS_INODE_MODE_FREE&&i->link_count==0U)return OPENFS_INODE_CORRUPT;if(i->extent_count>OPENFS_EXTENT_MAX)return OPENFS_INODE_CORRUPT;return OPENFS_INODE_OK;}
openfs_inode_result_t openfs_inode_read(const openfs_block_device_t*d,uint64_t start,uint64_t inode_number,uint64_t count,openfs_inode_t*out){if(!openfs_block_device_is_valid(d)||out==NULL)return OPENFS_INODE_INVALID_ARGUMENT;uint64_t block=0U;uint32_t within=0U;if(!locate(d,start,inode_number,count,&block,&within))return OPENFS_INODE_OUT_OF_RANGE;uint8_t*b=malloc(d->block_size);if(b==NULL)return OPENFS_INODE_IO_ERROR;if(d->read(d->context,start+block,1U,b)!=OPENFS_IO_OK){free(b);return OPENFS_INODE_IO_ERROR;}int ok=decode(b+within,out);free(b);return ok?openfs_inode_validate(out,count):OPENFS_INODE_CORRUPT;}
openfs_inode_result_t openfs_inode_write(const openfs_block_device_t*d,uint64_t start,uint64_t count,const openfs_inode_t*i){if(!openfs_block_device_is_valid(d)||i==NULL)return OPENFS_INODE_INVALID_ARGUMENT;if(openfs_inode_validate(i,count)!=OPENFS_INODE_OK)return OPENFS_INODE_CORRUPT;uint64_t block=0U;uint32_t within=0U;if(!locate(d,start,i->inode_number,count,&block,&within))return OPENFS_INODE_OUT_OF_RANGE;uint8_t*b=malloc(d->block_size);if(b==NULL)return OPENFS_INODE_IO_ERROR;if(d->read(d->context,start+block,1U,b)!=OPENFS_IO_OK){free(b);return OPENFS_INODE_IO_ERROR;}encode(i,b+within);openfs_io_result_t r=d->write(d->context,start+block,1U,b);free(b);return r==OPENFS_IO_OK?OPENFS_INODE_OK:OPENFS_INODE_IO_ERROR;}
