#include "openfs/metadata_root.h"
#include "openfs/metadata_cow.h"
#include <stdlib.h>
#include <string.h>
static uint16_t g16(const uint8_t*p){return (uint16_t)p[0]|((uint16_t)p[1]<<8U);}
static uint64_t g64(const uint8_t*p){uint64_t v=0U;for(unsigned i=0U;i<8U;i++)v|=(uint64_t)p[i]<<(8U*i);return v;}
static void p16(uint8_t*p,uint16_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8U);}
static void p64(uint8_t*p,uint64_t v){for(unsigned i=0U;i<8U;i++)p[i]=(uint8_t)(v>>(8U*i));}
static void payload_init(uint8_t*p,uint64_t gen){memset(p,0,56U);p16(p,(uint16_t)OPENFS_METADATA_ROOT_VERSION);p16(p+2U,(uint16_t)OPENFS_METADATA_ROOT_FLAG_LEGACY_LAYOUT);p64(p+8U,gen);}
static int payload_decode(const uint8_t*p,uint64_t gen,openfs_metadata_root_t*out){if(g16(p)!=(uint16_t)OPENFS_METADATA_ROOT_VERSION||((uint16_t)g16(p+2U)&(uint16_t)~OPENFS_METADATA_ROOT_FLAG_LEGACY_LAYOUT)!=0U||g64(p+8U)!=gen||gen==0U)return 0;out->version=g16(p);out->flags=g16(p+2U);out->generation=gen;out->inode_table_root=g64(p+16U);out->directory_root=g64(p+24U);out->extent_tree_root=g64(p+32U);out->xattr_root=g64(p+40U);out->snapshot_catalog_root=g64(p+48U);return 1;}
openfs_metadata_root_result_t openfs_metadata_root_initialize(openfs_block_device_t*d,const openfs_superblock_t*s,uint64_t block,uint64_t gen){if(!openfs_block_device_is_valid(d)||s==NULL||gen==0U)return OPENFS_METADATA_ROOT_INVALID_ARGUMENT;uint8_t*p=calloc(1U,d->block_size);if(p==NULL)return OPENFS_METADATA_ROOT_IO_ERROR;payload_init(p,gen);openfs_metadata_cow_result_t r=openfs_metadata_cow_initialize_block(d,s,block,OPENFS_METADATA_COW_TYPE_METADATA_ROOT,0U,gen,OPENFS_METADATA_ROOT_FLAG_LEGACY_LAYOUT,p);free(p);return r==OPENFS_METADATA_COW_OK?OPENFS_METADATA_ROOT_OK:(r==OPENFS_METADATA_COW_CORRUPT?OPENFS_METADATA_ROOT_CORRUPT:OPENFS_METADATA_ROOT_IO_ERROR);}
openfs_metadata_root_result_t openfs_metadata_root_read(const openfs_block_device_t*d,const openfs_superblock_t*s,uint64_t block,openfs_metadata_root_t*out){if(!openfs_block_device_is_valid(d)||s==NULL||out==NULL)return OPENFS_METADATA_ROOT_INVALID_ARGUMENT;openfs_metadata_cow_header_t h;openfs_metadata_cow_result_t r=openfs_metadata_cow_validate_block(d,s,block,&h);if(r!=OPENFS_METADATA_COW_OK)return r==OPENFS_METADATA_COW_CORRUPT?OPENFS_METADATA_ROOT_CORRUPT:OPENFS_METADATA_ROOT_IO_ERROR;if(h.type!=(uint16_t)OPENFS_METADATA_COW_TYPE_METADATA_ROOT||h.logical_id!=0U)return OPENFS_METADATA_ROOT_CORRUPT;uint8_t*p=malloc(d->block_size);if(p==NULL)return OPENFS_METADATA_ROOT_IO_ERROR;if(d->read(d->context,block,1U,p)!=OPENFS_IO_OK){free(p);return OPENFS_METADATA_ROOT_IO_ERROR;}int ok=payload_decode(p+OPENFS_METADATA_COW_HEADER_SIZE,h.generation,out);free(p);return ok?OPENFS_METADATA_ROOT_OK:OPENFS_METADATA_ROOT_CORRUPT;}
openfs_metadata_root_result_t openfs_metadata_root_update_generation(openfs_block_device_t*d,const openfs_superblock_t*s,uint64_t source,uint64_t gen,uint64_t*out){if(!openfs_block_device_is_valid(d)||s==NULL||out==NULL||gen==0U)return OPENFS_METADATA_ROOT_INVALID_ARGUMENT;openfs_metadata_root_t old;if(openfs_metadata_root_read(d,s,source,&old)!=OPENFS_METADATA_ROOT_OK)return OPENFS_METADATA_ROOT_CORRUPT;uint64_t target=0U;openfs_metadata_cow_result_t r=openfs_metadata_cow_copy_before_write(d,s,source,OPENFS_METADATA_COW_TYPE_METADATA_ROOT,0U,gen,&target);if(r!=OPENFS_METADATA_COW_OK)return r==OPENFS_METADATA_COW_CORRUPT?OPENFS_METADATA_ROOT_CORRUPT:OPENFS_METADATA_ROOT_IO_ERROR;uint8_t*p=calloc(1U,d->block_size);if(p==NULL){if(target!=source&&openfs_metadata_cow_release(d,s,target,NULL)!=OPENFS_METADATA_COW_OK)return OPENFS_METADATA_ROOT_CORRUPT;return OPENFS_METADATA_ROOT_IO_ERROR;}p16(p,(uint16_t)OPENFS_METADATA_ROOT_VERSION);p16(p+2U,old.flags);p64(p+8U,gen);p64(p+16U,old.inode_table_root);p64(p+24U,old.directory_root);p64(p+32U,old.extent_tree_root);p64(p+40U,old.xattr_root);p64(p+48U,old.snapshot_catalog_root);r=openfs_metadata_cow_write_payload(d,s,target,OPENFS_METADATA_COW_TYPE_METADATA_ROOT,0U,gen,old.flags,p);free(p);if(r!=OPENFS_METADATA_COW_OK){if(target!=source&&openfs_metadata_cow_release(d,s,target,NULL)!=OPENFS_METADATA_COW_OK)return OPENFS_METADATA_ROOT_CORRUPT;return r==OPENFS_METADATA_COW_CORRUPT?OPENFS_METADATA_ROOT_CORRUPT:OPENFS_METADATA_ROOT_IO_ERROR;}*out=target;return OPENFS_METADATA_ROOT_OK;}
