#include "openfs/path.h"
#include <string.h>
#include <stdlib.h>
#include <limits.h>
static openfs_path_result_t inode_count(const openfs_superblock_t *s,uint64_t *n){if(s->block_size!=0U&&s->inode_table_blocks>UINT64_MAX/s->block_size)return OPENFS_PATH_CORRUPT;*n=(s->inode_table_blocks*(uint64_t)s->block_size)/OPENFS_INODE_SIZE;return *n?OPENFS_PATH_OK:OPENFS_PATH_CORRUPT;}
static openfs_path_result_t read_inode(openfs_block_device_t*d,const openfs_superblock_t*s,uint64_t n,openfs_inode_t*i){uint64_t c=0U;if(inode_count(s,&c)!=OPENFS_PATH_OK)return OPENFS_PATH_CORRUPT;return openfs_inode_read(d,s->inode_table_start,n,c,i)==OPENFS_INODE_OK?OPENFS_PATH_OK:OPENFS_PATH_IO_ERROR;}
static openfs_path_result_t split_last(const char*p,char *parent,size_t ps,char *name,size_t ns){size_t len=strlen(p);if(len==0U||len>=ps)return OPENFS_PATH_INVALID_ARGUMENT;while(len>1U&&p[len-1U]=='/')--len;if(p[0]!='/')return OPENFS_PATH_INVALID_ARGUMENT;size_t slash=len;while(slash>0U&&p[slash-1U]!='/')--slash;if(slash==0U)return OPENFS_PATH_INVALID_ARGUMENT;size_t nl=len-slash;if(nl==0U||nl>=ns)return OPENFS_PATH_NAME_TOO_LONG;memcpy(name,p+slash,nl);name[nl]='\0';if(slash==1U){parent[0]='/';parent[1]='\0';}else{if(slash>=ps)return OPENFS_PATH_INVALID_ARGUMENT;memcpy(parent,p,slash-1U);parent[slash-1U]='\0';}return OPENFS_PATH_OK;}
static openfs_path_result_t find_parent(openfs_block_device_t*d,const openfs_superblock_t*s,const char*p,uint64_t*n){char pp[1024],name[OPENFS_DIR_NAME_MAX+1U];openfs_path_result_t r=split_last(p,pp,sizeof(pp),name,sizeof(name));if(r!=OPENFS_PATH_OK)return r;return openfs_path_lookup(d,s,pp,n);}
openfs_path_result_t openfs_path_lookup(openfs_block_device_t*d,const openfs_superblock_t*s,const char*p,uint64_t*out){if(d==NULL||s==NULL||p==NULL||out==NULL||p[0]!='/')return OPENFS_PATH_INVALID_ARGUMENT;if(strcmp(p,"/")==0){*out=s->root_inode;return OPENFS_PATH_OK;}char buf[1024];size_t len=strlen(p);if(len>=sizeof(buf))return OPENFS_PATH_NAME_TOO_LONG;memcpy(buf,p,len+1U);uint64_t cur=s->root_inode;char *part=strtok(buf,"/");while(part){if(part[0]=='\0')return OPENFS_PATH_INVALID_ARGUMENT;openfs_inode_t dir;if(read_inode(d,s,cur,&dir)!=OPENFS_PATH_OK)return OPENFS_PATH_IO_ERROR;if(dir.mode!=OPENFS_INODE_MODE_DIRECTORY)return OPENFS_PATH_NOT_DIRECTORY;openfs_dir_entry_t e;if(openfs_dir_lookup(d,s,&dir,part,&e)!=OPENFS_DIR_OK)return OPENFS_PATH_NOT_FOUND;cur=e.inode_number;part=strtok(NULL,"/");}*out=cur;return OPENFS_PATH_OK;}
openfs_path_result_t openfs_path_create(openfs_block_device_t*d,const openfs_superblock_t*s,const char*p,uint32_t mode,uint64_t*out){if(d==NULL||s==NULL||p==NULL||out==NULL)return OPENFS_PATH_INVALID_ARGUMENT;char pp[1024],name[OPENFS_DIR_NAME_MAX+1U];openfs_path_result_t r=split_last(p,pp,sizeof(pp),name,sizeof(name));if(r!=OPENFS_PATH_OK)return r;uint64_t parent=0U;if(openfs_path_lookup(d,s,pp,&parent)!=OPENFS_PATH_OK)return OPENFS_PATH_NOT_FOUND;openfs_inode_t pi;if(read_inode(d,s,parent,&pi)!=OPENFS_PATH_OK||pi.mode!=OPENFS_INODE_MODE_DIRECTORY)return OPENFS_PATH_NOT_DIRECTORY;openfs_dir_entry_t exists;if(openfs_dir_lookup(d,s,&pi,name,&exists)==OPENFS_DIR_OK)return OPENFS_PATH_EXISTS;uint64_t ino=0U;if(openfs_inode_alloc(d,s,parent,mode,&ino)!=OPENFS_INODE_ALLOC_OK)return OPENFS_PATH_NO_SPACE;openfs_dir_entry_t e={ino,1U,(uint8_t)(mode==OPENFS_INODE_MODE_DIRECTORY?2U:1U)};if(openfs_dir_add(d,s,&pi,name,&e)!=OPENFS_DIR_OK){openfs_inode_t dead;if(read_inode(d,s,ino,&dead)==OPENFS_PATH_OK){dead.mode=OPENFS_INODE_MODE_FREE;dead.link_count=0U;(void)openfs_inode_write(d,s->inode_table_start,(s->inode_table_blocks*(uint64_t)s->block_size)/OPENFS_INODE_SIZE,&dead);(void)openfs_inode_free(d,s,ino);}return OPENFS_PATH_IO_ERROR;}if(out)*out=ino;return OPENFS_PATH_OK;}
openfs_path_result_t openfs_path_mkdir(openfs_block_device_t*d,const openfs_superblock_t*s,const char*p,uint64_t*out){return openfs_path_create(d,s,p,OPENFS_INODE_MODE_DIRECTORY,out);}
openfs_path_result_t openfs_path_unlink(openfs_block_device_t*d,const openfs_superblock_t*s,const char*p){char pp[1024],name[OPENFS_DIR_NAME_MAX+1U];openfs_path_result_t r=split_last(p,pp,sizeof(pp),name,sizeof(name));if(r!=OPENFS_PATH_OK)return r;uint64_t parent=0U;if(openfs_path_lookup(d,s,pp,&parent)!=OPENFS_PATH_OK)return OPENFS_PATH_NOT_FOUND;openfs_inode_t pi;if(read_inode(d,s,parent,&pi)!=OPENFS_PATH_OK||pi.mode!=OPENFS_INODE_MODE_DIRECTORY)return OPENFS_PATH_NOT_DIRECTORY;openfs_dir_entry_t e;if(openfs_dir_lookup(d,s,&pi,name,&e)!=OPENFS_DIR_OK)return OPENFS_PATH_NOT_FOUND;openfs_inode_t target;if(read_inode(d,s,e.inode_number,&target)!=OPENFS_PATH_OK)return OPENFS_PATH_IO_ERROR;if(target.mode==OPENFS_INODE_MODE_DIRECTORY&&target.size!=0U)return OPENFS_PATH_INVALID_ARGUMENT;if(openfs_dir_remove(d,s,&pi,name)!=OPENFS_DIR_OK)return OPENFS_PATH_IO_ERROR;if(target.link_count>0U)target.link_count--;if(target.link_count==0U){if(target.blocks!=0U)return OPENFS_PATH_IO_ERROR;target.mode=OPENFS_INODE_MODE_FREE;}uint64_t c=0U;if(inode_count(s,&c)!=OPENFS_PATH_OK)return OPENFS_PATH_CORRUPT;if(openfs_inode_write(d,s->inode_table_start,c,&target)!=OPENFS_INODE_OK)return OPENFS_PATH_IO_ERROR;if(target.mode==OPENFS_INODE_MODE_FREE&&(openfs_inode_free(d,s,e.inode_number)!=OPENFS_INODE_ALLOC_OK))return OPENFS_PATH_IO_ERROR;return OPENFS_PATH_OK;}
openfs_path_result_t openfs_path_rename(openfs_block_device_t*d,const openfs_superblock_t*s,const char*oldp,const char*newp){char op[1024],on[OPENFS_DIR_NAME_MAX+1U],np[1024],nn[OPENFS_DIR_NAME_MAX+1U];if(split_last(oldp,op,sizeof(op),on,sizeof(on))!=OPENFS_PATH_OK||split_last(newp,np,sizeof(np),nn,sizeof(nn))!=OPENFS_PATH_OK)return OPENFS_PATH_INVALID_ARGUMENT;uint64_t oi=0U,npid=0U;if(openfs_path_lookup(d,s,oldp,&oi)!=OPENFS_PATH_OK)return OPENFS_PATH_NOT_FOUND;if(openfs_path_lookup(d,s,np,&npid)!=OPENFS_PATH_OK)return OPENFS_PATH_NOT_FOUND;if(oi==npid)return OPENFS_PATH_INVALID_ARGUMENT;openfs_inode_t od,nd;if(read_inode(d,s,oi,&od)!=OPENFS_PATH_OK||read_inode(d,s,npid,&nd)!=OPENFS_PATH_OK)return OPENFS_PATH_IO_ERROR;openfs_dir_entry_t e;if(openfs_dir_lookup(d,s,&od,on,&e)!=OPENFS_DIR_OK)return OPENFS_PATH_NOT_FOUND;openfs_dir_entry_t exists;if(openfs_dir_lookup(d,s,&nd,nn,&exists)==OPENFS_DIR_OK)return OPENFS_PATH_EXISTS;if(openfs_dir_remove(d,s,&od,on)!=OPENFS_DIR_OK)return OPENFS_PATH_IO_ERROR;if(openfs_dir_add(d,s,&nd,nn,&e)!=OPENFS_DIR_OK){(void)openfs_dir_add(d,s,&od,on,&e);return OPENFS_PATH_IO_ERROR;}od.parent_inode=npid;uint64_t c=0U;if(inode_count(s,&c)!=OPENFS_PATH_OK||openfs_inode_write(d,s->inode_table_start,c,&od)!=OPENFS_INODE_OK)return OPENFS_PATH_IO_ERROR;return OPENFS_PATH_OK;}
