#include "openfs/transaction.h"
#include <stdlib.h>
#include <string.h>
struct openfs_transaction_pending { uint64_t block; uint8_t *data; };
static openfs_io_result_t tx_read(void *ctx,uint64_t first,uint32_t count,void*out){openfs_transaction_t*t=ctx;if(t==NULL||t->base==NULL||out==NULL||count==0U||first>=t->base->block_count||(uint64_t)count>t->base->block_count-first)return OPENFS_IO_OUT_OF_RANGE;for(uint32_t i=0U;i<count;i++){uint64_t b=first+(uint64_t)i;uint8_t*dst=(uint8_t*)out+(size_t)((uint64_t)i*t->base->block_size);int found=0;for(uint64_t n=0U;n<t->pending_count;n++)if(t->pending[n].block==b){memcpy(dst,t->pending[n].data,t->base->block_size);found=1;break;}if(!found&&t->base->read(t->base->context,b,1U,dst)!=OPENFS_IO_OK)return OPENFS_IO_IO_ERROR;}return OPENFS_IO_OK;}
static openfs_io_result_t tx_write(void *ctx,uint64_t first,uint32_t count,const void*in){openfs_transaction_t*t=ctx;if(t==NULL||t->base==NULL||in==NULL||count==0U)return OPENFS_IO_OUT_OF_RANGE;if(t->failed||t->commit_started)return OPENFS_IO_IO_ERROR;if(first>=t->base->block_count||(uint64_t)count>t->base->block_count-first)return OPENFS_IO_OUT_OF_RANGE;for(uint32_t i=0U;i<count;i++){uint64_t b=first+(uint64_t)i;const uint8_t*src=(const uint8_t*)in+(size_t)((uint64_t)i*t->base->block_size);uint64_t idx=t->pending_count;for(uint64_t n=0U;n<t->pending_count;n++)if(t->pending[n].block==b){idx=n;break;}int new_entry=idx==t->pending_count;if(new_entry){if(t->pending_count==t->pending_capacity){uint64_t cap=t->pending_capacity==0U?8U:t->pending_capacity*2U;if(cap<t->pending_capacity||cap>SIZE_MAX/sizeof(*t->pending))return OPENFS_IO_IO_ERROR;openfs_transaction_pending_t*p=realloc(t->pending,(size_t)cap*sizeof(*p));if(p==NULL)return OPENFS_IO_IO_ERROR;t->pending=p;t->pending_capacity=cap;}t->pending[idx].data=malloc(t->base->block_size);if(t->pending[idx].data==NULL)return OPENFS_IO_IO_ERROR;t->pending[idx].block=b;}openfs_journal_result_t jr=openfs_journal_write_block(t->journal,t->base,t->txid,b,src);if(jr!=OPENFS_JOURNAL_OK){t->failed=1;if(new_entry){free(t->pending[idx].data);t->pending[idx].data=NULL;t->pending[idx].block=0U;}return OPENFS_IO_IO_ERROR;}memcpy(t->pending[idx].data,src,t->base->block_size);if(new_entry)t->pending_count++;}return OPENFS_IO_OK;}
static openfs_io_result_t tx_flush(void*ctx){openfs_transaction_t*t=ctx;if(t==NULL||t->base==NULL)return OPENFS_IO_IO_ERROR;return OPENFS_IO_OK;}
static void clear(openfs_transaction_t*t){if(t->pending!=NULL){for(uint64_t i=0U;i<t->pending_count;i++)free(t->pending[i].data);free(t->pending);}t->pending=NULL;t->pending_count=0U;t->pending_capacity=0U;}
openfs_transaction_result_t openfs_transaction_begin(openfs_transaction_t*t,openfs_block_device_t*base,openfs_journal_t*j){if(t==NULL||!openfs_block_device_is_valid(base)||j==NULL)return OPENFS_TRANSACTION_INVALID_ARGUMENT;memset(t,0,sizeof(*t));t->base=base;t->journal=j;openfs_journal_result_t jr=openfs_journal_begin(j,base,&t->txid);if(jr!=OPENFS_JOURNAL_OK)return jr==OPENFS_JOURNAL_FULL?OPENFS_TRANSACTION_FULL:OPENFS_TRANSACTION_IO_ERROR;t->device.context=t;t->device.block_size=base->block_size;t->device.block_count=base->block_count;t->device.read=tx_read;t->device.write=tx_write;t->device.flush=tx_flush;t->active=1;return OPENFS_TRANSACTION_OK;}
openfs_block_device_t*openfs_transaction_device(openfs_transaction_t*t){return t!=NULL&&t->active?&t->device:NULL;}
openfs_transaction_result_t openfs_transaction_commit(openfs_transaction_t*t){if(t==NULL||!t->active||t->journal==NULL||t->base==NULL)return OPENFS_TRANSACTION_INVALID_ARGUMENT;if(t->failed||t->commit_started)return OPENFS_TRANSACTION_IO_ERROR;t->commit_started=1;openfs_journal_result_t jr=openfs_journal_commit(t->journal,t->base,t->txid);if(jr!=OPENFS_JOURNAL_OK){t->failed=1;t->commit_started=(jr==OPENFS_JOURNAL_FULL)?0:1;return jr==OPENFS_JOURNAL_FULL?OPENFS_TRANSACTION_FULL:OPENFS_TRANSACTION_IO_ERROR;}t->committed=1;for(uint64_t i=0U;i<t->pending_count;i++){if(t->base->write(t->base->context,t->pending[i].block,1U,t->pending[i].data)!=OPENFS_IO_OK){t->failed=1;return OPENFS_TRANSACTION_IO_ERROR;}}if(t->base->flush(t->base->context)!=OPENFS_IO_OK){t->failed=1;return OPENFS_TRANSACTION_IO_ERROR;}if(openfs_journal_checkpoint(t->journal,t->base)!=OPENFS_JOURNAL_OK){t->failed=1;return OPENFS_TRANSACTION_IO_ERROR;}clear(t);t->active=0;return OPENFS_TRANSACTION_OK;}
openfs_transaction_result_t openfs_transaction_abort(openfs_transaction_t*t){if(t==NULL||!t->active||t->journal==NULL||t->base==NULL)return OPENFS_TRANSACTION_INVALID_ARGUMENT;if(t->commit_started){clear(t);t->active=0;return OPENFS_TRANSACTION_OK;}t->journal->active_transaction_id=0U;openfs_journal_result_t jr=openfs_journal_checkpoint(t->journal,t->base);clear(t);t->active=0;return jr==OPENFS_JOURNAL_OK?OPENFS_TRANSACTION_OK:OPENFS_TRANSACTION_IO_ERROR;}
